# Generated by Django 5.1.3 on 2024-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainblock',
            name='proof',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
